version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "conda activate midas-py310 && gunicorn -w 2 -b 0.0.0.0:443 outscript:app"
    ports:
      - "443:443"