version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "source activate midas-py310 && gunicorn -w 2 -b 0.0.0.0:8000 outscript:app"
    ports:
      - "8000:8000"