name: midas-py310
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10.8
  - pytorch::pytorch=1.13.0
  - torchvision=0.14.0
  - pip=22.3.1
  - numpy=1.23.4
  - pip:
    - opencv-python-headless
    - imutils==0.5.4
    - timm==0.6.12
    - einops==0.6.0
    - flask
    - flask-limiter
    - gunicorn